[10:41:52 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: rawOrder is not defined\n    at Object.<anonymous> (D:\\lab_node\\controllers\\vnpay.js:562:17)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\routes\\vnpay.js:2:25)","name":"ReferenceError","message":"rawOrder is not defined"}
[10:42:11 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: rawOrder is not defined\n    at Object.<anonymous> (D:\\lab_node\\controllers\\vnpay.js:562:17)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\routes\\vnpay.js:2:25)","name":"ReferenceError","message":"rawOrder is not defined"}
[10:42:41 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: rawOrder is not defined\n    at Object.<anonymous> (D:\\lab_node\\controllers\\vnpay.js:562:17)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\routes\\vnpay.js:2:25)","name":"ReferenceError","message":"rawOrder is not defined"}
[10:43:19 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"ReferenceError: rawOrder is not defined\n    at Object.<anonymous> (D:\\lab_node\\controllers\\vnpay.js:574:17)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\routes\\vnpay.js:2:25)","name":"ReferenceError","message":"rawOrder is not defined"}
[11:06:00 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:333:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[12:36:37 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:95:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[12:46:07 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:96:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[12:46:22 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as post] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:96:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.post() requires a callback function but got a [object Undefined]"}
[13:20:23 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:352:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[13:25:59 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"D:\\lab_node\\controllers\\services.js:63\n        const finalCategories = serviceCategories.length > 0 ? serviceCategories : fallbackCategories;\n              ^\n\nSyntaxError: Identifier 'finalCategories' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1486:18)\n    at Module._compile (node:internal/modules/cjs/loader:1528:20)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\lab_node\\routes\\services.js:3:28)","name":"SyntaxError","message":"Identifier 'finalCategories' has already been declared"}
[18:00:41 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:360:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[18:26:10 21/07/2025] [ERROR] ❌ Lỗi khi gửi email | Meta: {}
[20:55:48 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:360:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[20:59:04 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:360:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[21:00:25 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:360:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[21:02:58 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:360:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[21:04:49 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:360:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[21:06:15 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:360:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[21:20:20 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (D:\\lab_node\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\lab_node\\app.js:360:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","name":"Error","message":"listen EADDRINUSE: address already in use :::5000"}
[21:48:38 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:185:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
[21:50:11 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:186:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
[21:51:48 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:186:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
[21:52:57 21/07/2025] [ERROR] Uncaught Exception | Meta: {"fatal":true,"stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\route.js:216:15)\n    at proto.<computed> [as get] (D:\\lab_node\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\lab_node\\routes\\admin.js:186:8)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)","name":"Error","message":"Route.get() requires a callback function but got a [object Undefined]"}
